SET SEARCH_PATH to 'douaisis', public;

ALTER TABLE parcellaire ADD COLUMN IF NOT EXISTS typproprietaire TEXT;


/*
	CCOGRM: 
    1   ETAT    
    2   REGION
    3   DEPARTEMENT
    4   COMMUNE
    5   OFFICE HLM
    6   EPCI
    7   COPROPRIETES
    8   PERSONNES PHYSIQUES
    9   ETABLISSEMENTS PUBLICS OU ORGANISMES ASSIMILES
    0   PERSONNES MORALES PRIVEES
    11  EPF
*/


/* classes disponibles:
Foncier considéré comme maitrisé :
	- COMMUNE
	- EPCI
	- EPF
	- AMENAGEUR_PUB
		- EPA
		- SEM locales ou autres identifiés comme aménageurs partenaires
Foncier considéré comme non maitrisé :
	- AUTRE_PUB
		- état, région, département
		- mais aussi éventuellement autres SEM,SIVOM/SIVU? CCAS ? 
		- bailleurs sociaux, etc, non considérés comme partenaires ?
	- PRIVE (personnes morales ou publiques)
	- COPROPRIETE

*/

UPDATE parcellaire SET typproprietaire = 
	CASE 
	-- identification EPF
		WHEN ddenomproppro ilike 'ETABLISSEMENT PUBLIC FONCIER IDF' THEN 'EPF'
		WHEN ddenomproppro ilike 'FONCIER LANDES FONCIER' THEN 'EPF'
		-- Douaisis
		WHEN ddenomproppro ilike 'ETS PUBLIC FONCIER NORD PAS DE CALAIS' THEN 'EPF'
		-- CLM
		WHEN ddenomproppro ilike 'ETABLISSEMENT PUBLIC FONCIER DE NORMANDIE' THEN 'EPF'
		WHEN ddenomproppro ilike 'FONCIER DE NORMANDIE%' THEN 'EPF'

	-- identification EPA et Autres aménageurs publics
		WHEN ddenomproppro ilike 'EPA SENART' THEN 'AMENAGEUR_PUB'
		WHEN ddenomproppro ilike 'GRAND PARIS AMENAGEMENT%' THEN 'AMENAGEUR_PUB'
		WHEN ddenomproppro ilike 'SA IMMOBI ECONOMIE MIXTE CORBEIL ESSONNE' THEN 'AMENAGEUR_PUB'

		WHEN ddenomproppro ilike 'ETS PUBLIC D AMENAGEMENT DE LA VILLE NOUVELLE DU VAUDREUIL' THEN 'AMENAGEUR_PUB'
		WHEN ddenomproppro ilike 'SOCIETE HEROUVILLAISE D''ECONOMIE MIXTE POUR L''AMENAGEMENT' THEN 'AMENAGEUR_PUB'
		WHEN ddenomproppro ilike 'NORMANDIE AMENAGEMENT' THEN 'AMENAGEUR_PUB'


	-- identification EPCI

		-- EPA SENART
		WHEN ddenomproppro ilike 'GRAND PARIS SUD' THEN  'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE DE COMMUNES DU VAL D ESSONNE' THEN  'EPCI'
		WHEN ddenomproppro ilike 'CA DE SENART' THEN  'EPCI'
		WHEN ddenomproppro ilike 'CA GRAND PARIS SUD SEINE ESSONNE SENART' THEN  'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE AGGLO EVRY CENTRE ESSONNE' THEN  'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE AGGLOMERATION SEINE ESSONNE' THEN  'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE D AGGLOMERATION LES LACS DE L ESSONNE' THEN  'EPCI'
		WHEN ddenomproppro ilike 'SYND AGGLO NOUVELLE DE SENART EN ESSONNE' THEN  'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE DE COMMUNES EURE MADRIE SEINE' THEN 'EPCI'
		WHEN ddenomproppro ilike 'CA VAL D''EUROPE AGGLOMERATION' THEN 'EPCI'
		-- MACS
		WHEN ddenomproppro ilike 'COMMUNAUTE DE COMMUNES MAREMNE ADOUR COTE SUD' THEN 'EPCI'
		-- GPSEO
		WHEN ddenomproppro ilike 'COMMUNAUTE D''AGGLOMERATION SEINE EURE' THEN 'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE D AGGLOMERATION SEINE EURE' THEN 'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE D AGGLOMERATIONS EURE SEINE' THEN 'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE D AGGLOMERATIONS EURE SEINE PATINOIRE' THEN 'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE D''AGGLOMERATION DES PORTES DE L''EURE' THEN 'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE DE COMMUNES DES ANDELYS ET DE SES ENVIRONS' THEN 'EPCI'
		-- CLM
		WHEN ddenomproppro ilike 'COMMUNAUTE COMMUNES ENTRE THUE ET MUE' THEN 'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE COMMUNES PLAINE SUD DE CAEN' THEN 'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE D AGGLOMERATION DE CAEN LA MER' THEN 'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE D''AGGLOMERATION CAEN LA MER' THEN 'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE DE COMMUNES RIVES DE L''ODON' THEN 'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE URBAINE CAEN LA MER' THEN 'EPCI'
		WHEN ddenomproppro ilike 'CU CAEN LA MER' THEN 'EPCI'
		-- Limoges
		WHEN ddenomproppro ilike 'COMMUNAUTE DE COMMUNES DU VAL DE VIENNE' THEN 'EPCI'
		WHEN ddenomproppro ilike 'COMMUNAUTE DE COMMUNES L''AURENCE GLANE DEVELOPPEMENT' THEN 'EPCI'
		WHEN ddenomproppro ilike 'CU LIMOGES METROPOLE' THEN 'EPCI'

		-- Douaisis
		WHEN ddenomproppro ilike 'COMMUNE	COMMUNAUTE D''AGGLOMERATION DU DOUAISIS' THEN 'EPCI'
		WHEN ddenomproppro ilike 'DOUAISIS AGGLO' THEN 'EPCI'
		
	
		WHEN ddenomproppro ilike 'COMMUNAUTE DE COMMUNES%' THEN 'EPCI'
		
	
	
	-- Identification Communes
		-- EPA SENART
		WHEN ddenomproppro ilike 'SAVIGNY LE TEMPLE' THEN 'COMMUNE'
		WHEN ddenomproppro ilike 'CENTRE COMMUNAL D ACTION SOCIALE DE CORBEIL' THEN 'COMMUNE'
		
		-- VAL D'HAZEY
		WHEN ddenomproppro ilike 'COMMUNE DE SAINT PIERRE LA GARENNE' THEN 'COMMUNE'
		-- CLM
		WHEN ddenomproppro ilike 'BUREAU D AIDE SOCIALE DE LA VILLE DE LISIEUX' THEN 'COMMUNE'
		WHEN ddenomproppro ilike 'BUREAU D AIDE SOCIALE DE LA COMMUNE DE DEMOUVILLE' THEN 'COMMUNE'
		WHEN ddenomproppro ilike 'CENTRE COMMUNAL D''ACTION SOCIALE' THEN 'COMMUNE'



	-- identification AUTRE_PUB
		-- GPSUD
		WHEN ddenomproppro ilike 'PORTE SUD DU GRAND PARIS' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'DIRECTION NATIONALE INTERVENTIONS DOMANIALES DNID' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'CENTRE HOSPITALIER SUD FRANCILIEN' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'AGCE ESPACES VERTS REGION ILE DE FRANCE' THEN 'AUTRE_PUB' -- REGION
		-- VAL D'HAZEY
		WHEN ddenomproppro ilike 'SETOM DES COMMUNES DU SUD DU DEPARTEMENT DE L EURE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT MIXTE POUR L''ETUDE ET LE TRAITEMENT DES ORDURES MEN' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'IMMOBILIERE BASSE SEINE%' THEN 'AUTRE_PUB'
		-- CLM
		WHEN ddenomproppro ilike 'ADMINISTRATION DES ARMEES SERVICE DU GENIE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'AGENCE DE L EAU' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'AGENCE DE L''EAU SEINE-NORMANDIE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'C A U E DU CALVADOS' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'CAISSE ALLOCATIONS FAMILIALES 14' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'CENTRE HOSPITALIER REGIONAL DE CAEN' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'CENTRE HOSPITALIER REGIONAL   HOSPICE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'CHAMBRE DES METIERS ET ARTISANAT INTERDEPTALE CALVADOS ORNE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'ETAT SERVICE DES DOMAINES' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'PAR LE MINIS DE L EQUIPEMENT SERVICE DES PONTS ET CHAUSSEES' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'REGION DE BASSE NORMANDIE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SERVICE DEPART INCENDIE ET DE SECOURS DU CALVADOS' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SOCIETE D''AMENAGEMENT FONCIER ET D''ETABLISSEMENT RURAL DE NO' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SOLIHA TERRITOIRES EN NORMANDIE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SIVOM DES TROIS VALLEES' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SIVOM DU GRAND ODON' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SI ALIMENTATION EN EAU POTABLE LOUVIGNY' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SM DE PRODUCTION ET DE DISTRIBUTION D''EAU POTABLE DE LA REGI' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SM TRANSPORTS EN COMMUN AGGLOMERATION CAENNAISE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYND INTERCOM DE LA SOURCE DE THAON  MAIRIE D ANGUERNY' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYND INTERCOMM D ASSAIN DE LA VALLEE DU DAN' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT D ADDUCTION D EAU POTABLE DE COULOMBS' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT D ADDUCTION D EAU POTABLE SANNERVILLE TOUFFREVILLE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT D ALIMENTATION EAU POTABLE DE LA REGION DE MAY SUR' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT D ASSAINISSEMENT SIGO' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT D''ALIMENTATION EN EAU DE LA REGION DE MAY SUR ORNE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT D''ASSAINISSEMENT PORTE SUD' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT DE DISTRIBUTION D EAU DE COLLEVILLE HERMANVILLE   M' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT DE VALORISATION ET D''ELIMINATION DES DECHETS' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT DES EAUX BRETTEVILLE L''ORGUEILLEUSE   MAIRIE DE BRE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT DES EAUX DE BRETTEVILLE L''ORGUEILLEUSE   MAIRIE DE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT DES EAUX ET D ASSAINISSEMENT DE DEMOUVILLE CUVERVIL' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT DES ECOLES MATERNELLE ET PRIMAIRE DE TROARN' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT EAU POTABLE DE TROARN ET SAINT PAIR   MAIRIE DE TRO' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTER D ALIM EN EAU REG COULOMBS' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERC D''ASSAINISSEMENT DE LA VALLEE DU DAN' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOM  D''ASSAINISSEMENT DU VAL DE FONTENAY' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOM D ENERGIES ET D EQUIPEMENT DU CALVADOS' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMM D''ADDUCTION EAU POTABLE CAEN-OUEST' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL A VOCATION MULTIPLE DU GRAND ODON' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL A VOCATION MULTIPLE DU GRAND ODON   M' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL A VOCATION UNIQUE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL CAEN HEROUVILLE BIEVILLE EPRON' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL D ASSAINISSEMENT   MAIRIE DE HERMANVI' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL D ASSAINISSEMENT DE SAINT ANDRE SAINT' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL D ASSAINISSEMENT DU VAL DE FONTENAY' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL D ENERGIES ET D EQUIPEMENT DU CALVADO' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL D''ADDUCTION D''EAU POTABLE DE LA REGIO' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL D''ASSAINISSEMENT DE LA VALLEE DU DAN' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL D''ASSAINISSEMENT DE SOLIERS GRENTHEVI' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL D''ASSAINISSEMENT DE ST ANDRE SUR ORNE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL D''ASSAINISSEMENT ST ANDRE MAY ST MART' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL DE CAEN HEROUVILL BIEVILLE EPRON' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL DE CAEN HEROUVILLE BIEVILLE EPRON' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL DE LA VALLEE DU DAN   MAIRIE DE BENOU' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL DU GRAND ODON  MAIRIE DE VERSON' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL EN EAU   MAIRIE D HERMANVILLE SUR MER' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL POUR L''ASSAINISSEMENT ET L''EVACUATION' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT INTERCOMMUNAL POUR LA VALORISATION ET L''ELIMINATION' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT MIXTE D ASSAINISSEMENT DE LA ZONE NORD OUEST DE AGG' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT MIXTE ET REALISATION DES TRAVAUX D UN CENTRE ROUTIE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT MIXTE POUR LA LUTTE CONTRE LES INNONDATIONS DE LA V' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT MIXTE TRAITEMENT VALORISATION DES DECHETS MENAGERS' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT MIXTE USINE CAPTAGE D EAU   MAIRIE DE CAEN' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'SYNDICAT POUR LA VALORISATION ET L''ELIMINATION DES DECHETS D' THEN 'AUTRE_PUB'

		-- Limoges
		WHEN ddenomproppro ilike 'OFFICE PUBLIC DE L HABITAT 87' THEN 'AUTRE_PUB'
		WHEN ddenomproppro ilike 'CAISSE ALLOCATIONS FAMILIALE' THEN 'AUTRE_PUB'
		WHEN ddenomproppro in ('CH  COMMERCE INDUSTRIE LIMOGES HTE VIENN',
			'CHAMBRE D AGRICULTURE DE LA HAUTE VIENNE',
			'CHAMBRE DE COMMERCE ET D INDUSTRIE DE LIMOGES',
			'CHAMBRE DES METIERS DE LA HAUTE VIENNE',
			'CHAMBRE REG DE METIERS ET DE L''ARTISANAT DU LIMOUSIN') THEN 'AUTRE_PUB'

		-- Douaisis
		WHEN ddenomproppro ilike 'COMMUNAUTE D''AGGLOMERATION D''HENIN-CARVIN' THEN 'AUTRE_PUB'


	

	-- identification ETAT
		WHEN ddenomproppro ilike 'ETAT' THEN 'AUTRE_PUB'
		WHEN ddenomproppro in (
			'DIRECTION DEPARTEMENTALE DE L EQUIPEMENT',
			'MINISTERE DES TRANSPORTS',
			'BPIFRANCE FINANCEMENT'
			) THEN 'AUTRE_PUB'

	-- classification autres propriétaires
		WHEN typproppro ilike 'EPCI%' THEN 'EPCI'
		WHEN typproppro ilike 'COMMUNE%' THEN 'COMMUNE'
		

		WHEN typproppro ilike 'DEPARTEMENT%' THEN 'AUTRE_PUB'
		WHEN typproppro ilike 'REGION%' THEN 'AUTRE_PUB'
		WHEN typproppro ilike 'ETAT%' THEN 'AUTRE_PUB'
		WHEN typproppro ilike 'OFFICE HLM%' THEN 'AUTRE_PUB'
		WHEN typproppro ilike 'ETABLISSEMENT PUBLIC%' THEN 'AUTRE_PUB'
		WHEN typproppro ilike 'ETABLISSEMENTS PUBLIC%' THEN 'AUTRE_PUB'
		
		WHEN typproppro ilike 'COPROP%' THEN 'COPROPRIETE'
		ELSE  'PRIVE' 
	END;