[project]
name = "urbaflow"
version = "0.1.0"
description = "Intégration des données liées à l'urbanisme"
authors = [{ name = "Thomas Brosset", email = "thomas.brosset@gmail.com" }]
requires-python = ">=3.10"
dependencies = [
	"aiosqlite>=0.21.0",
	"chardet>=5.2.0",
	"duckdb>=1.0.0",
	"geoalchemy2>=0.13.3",
	"geopandas>=0.13.2",
	"owslib>=0.31.0",
	"pandas>=2.0.2",
	"prefect>=3.0.0",
	"psycopg2-binary>=2.9.6",
	"python-dotenv>=1.0.0",
	"pytz>=2023.3",
	"simplejson>=3.19.1",
	"sqlalchemy>=2.0.16",
	"sqlparse>=0.5.2",
	"typer>=0.12.3",
]

[dependency-groups]
dev = [
	"coverage>=7.6.9",
	"ipykernel>=6.29.4",
	"isort>=5.12.0",
	"pre-commit>=4.6.2",
	"pylint>=2.17.5",
	"pytest>=8.3.4",
	"ruff>=0.16.8",
	"sqlfluff>=3.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.sqlfluff.indentation]
indent_unit = "space"
tab_space_size = 4

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]