DROP TABLE IF EXISTS correction_typologie_proprietaire;

CREATE TABLE correction_typologie_proprietaire (
    ddenom text,
    catpro text
);
-- Création d'une clé primaire pour éviter les doublons
-- et assurer la rapidité de la jointure
ALTER TABLE correction_typologie_proprietaire ADD PRIMARY KEY (ddenom);

-- Insertion des catpros de propriétaires identifiées manuellement
-- une ligne par propriétaire 
-- (disable LT05 pour éviter les warnings sur la longueur de la ligne)
-- noqa: disable=LT05
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('ETABLISSEMENT PUBLIC FONCIER IDF', 'EPF');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('FONCIER LANDES FONCIER', 'EPF');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('ETS PUBLIC FONCIER NORD PAS DE CALAIS', 'EPF');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('ETABLISSEMENT PUBLIC FONCIER DE NORMANDIE', 'EPF');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('FONCIER DE NORMANDIE', 'EPF');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('EPA SENART', 'AMENAGEUR_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('GRAND PARIS AMENAGEMENT', 'AMENAGEUR_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SA IMMOBI ECONOMIE MIXTE CORBEIL ESSONNE', 'AMENAGEUR_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('ETS PUBLIC D AMENAGEMENT DE LA VILLE NOUVELLE DU VAUDREUIL', 'AMENAGEUR_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SOCIETE HEROUVILLAISE D''ECONOMIE MIXTE POUR L''AMENAGEMENT', 'AMENAGEUR_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('NORMANDIE AMENAGEMENT', 'AMENAGEUR_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('GRAND PARIS SUD', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE DE COMMUNES DU VAL D ESSONNE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CA DE SENART', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CA GRAND PARIS SUD SEINE ESSONNE SENART', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE AGGLO EVRY CENTRE ESSONNE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE AGGLOMERATION SEINE ESSONNE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE D AGGLOMERATION LES LACS DE L ESSONNE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYND AGGLO NOUVELLE DE SENART EN ESSONNE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE DE COMMUNES EURE MADRIE SEINE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CA VAL D''EUROPE AGGLOMERATION', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE DE COMMUNES MAREMNE ADOUR COTE SUD', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE D''AGGLOMERATION SEINE EURE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE D AGGLOMERATION SEINE EURE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE D AGGLOMERATIONS EURE SEINE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE D AGGLOMERATIONS EURE SEINE PATINOIRE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE D''AGGLOMERATION DES PORTES DE L''EURE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE DE COMMUNES DES ANDELYS ET DE SES ENVIRONS', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE COMMUNES ENTRE THUE ET MUE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE COMMUNES PLAINE SUD DE CAEN', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE D AGGLOMERATION DE CAEN LA MER', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE D''AGGLOMERATION CAEN LA MER', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE DE COMMUNES RIVES DE L''ODON', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE URBAINE CAEN LA MER', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CU CAEN LA MER', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE DE COMMUNES DU VAL DE VIENNE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE DE COMMUNES L''AURENCE GLANE DEVELOPPEMENT', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CU LIMOGES METROPOLE', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNE  COMMUNAUTE D''AGGLOMERATION DU DOUAISIS', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('DOUAISIS AGGLO', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SAVIGNY LE TEMPLE', 'COMMUNE');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CENTRE COMMUNAL D ACTION SOCIALE DE CORBEIL', 'COMMUNE');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNE DE SAINT PIERRE LA GARENNE', 'COMMUNE');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('BUREAU D AIDE SOCIALE DE LA VILLE DE LISIEUX', 'COMMUNE');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('BUREAU D AIDE SOCIALE DE LA COMMUNE DE DEMOUVILLE', 'COMMUNE');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CENTRE COMMUNAL D''ACTION SOCIALE', 'COMMUNE');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('PORTE SUD DU GRAND PARIS', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('DIRECTION NATIONALE INTERVENTIONS DOMANIALES DNID', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CENTRE HOSPITALIER SUD FRANCILIEN', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('AGCE ESPACES VERTS REGION ILE DE FRANCE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SETOM DES COMMUNES DU SUD DU DEPARTEMENT DE L EURE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT MIXTE POUR L''ETUDE ET LE TRAITEMENT DES ORDURES MEN', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('IMMOBILIERE BASSE SEINE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('ADMINISTRATION DES ARMEES SERVICE DU GENIE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('AGENCE DE L EAU', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('AGENCE DE L''EAU SEINE-NORMANDIE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('C A U E DU CALVADOS', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CAISSE ALLOCATIONS FAMILIALES 14', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CENTRE HOSPITALIER REGIONAL DE CAEN', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CENTRE HOSPITALIER REGIONAL   HOSPICE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CHAMBRE DES METIERS ET ARTISANAT INTERDEPTALE CALVADOS ORNE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('ETAT SERVICE DES DOMAINES', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('PAR LE MINIS DE L EQUIPEMENT SERVICE DES PONTS ET CHAUSSEES', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('REGION DE BASSE NORMANDIE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SERVICE DEPART INCENDIE ET DE SECOURS DU CALVADOS', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SOCIETE D''AMENAGEMENT FONCIER ET D''ETABLISSEMENT RURAL DE NO', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SOLIHA TERRITOIRES EN NORMANDIE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SIVOM DES TROIS VALLEES', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SIVOM DU GRAND ODON', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SI ALIMENTATION EN EAU POTABLE LOUVIGNY', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SM DE PRODUCTION ET DE DISTRIBUTION D''EAU POTABLE DE LA REGI', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SM TRANSPORTS EN COMMUN AGGLOMERATION CAENNAISE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYND INTERCOM DE LA SOURCE DE THAON  MAIRIE D ANGUERNY', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYND INTERCOMM D ASSAIN DE LA VALLEE DU DAN', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT D ADDUCTION D EAU POTABLE DE COULOMBS', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT D ADDUCTION D EAU POTABLE SANNERVILLE TOUFFREVILLE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT D ALIMENTATION EAU POTABLE DE LA REGION DE MAY SUR', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT D ASSAINISSEMENT SIGO', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT D''ALIMENTATION EN EAU DE LA REGION DE MAY SUR ORNE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT D''ASSAINISSEMENT PORTE SUD', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT DE DISTRIBUTION D EAU DE COLLEVILLE HERMANVILLE   M', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT DE VALORISATION ET D''ELIMINATION DES DECHETS', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT DES EAUX BRETTEVILLE L''ORGUEILLEUSE   MAIRIE DE BRE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT DES EAUX DE BRETTEVILLE L''ORGUEILLEUSE   MAIRIE DE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT DES EAUX ET D ASSAINISSEMENT DE DEMOUVILLE CUVERVIL', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT DES ECOLES MATERNELLE ET PRIMAIRE DE TROARN', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT EAU POTABLE DE TROARN ET SAINT PAIR   MAIRIE DE TRO', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTER D ALIM EN EAU REG COULOMBS', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERC D''ASSAINISSEMENT DE LA VALLEE DU DAN', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOM  D''ASSAINISSEMENT DU VAL DE FONTENAY', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOM D ENERGIES ET D EQUIPEMENT DU CALVADOS', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMM D''ADDUCTION EAU POTABLE CAEN-OUEST', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL A VOCATION MULTIPLE DU GRAND ODON', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL A VOCATION MULTIPLE DU GRAND ODON   M', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL A VOCATION UNIQUE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL CAEN HEROUVILLE BIEVILLE EPRON', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL D ASSAINISSEMENT   MAIRIE DE HERMANVI', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL D ASSAINISSEMENT DE SAINT ANDRE SAINT', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL D ASSAINISSEMENT DU VAL DE FONTENAY', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL D ENERGIES ET D EQUIPEMENT DU CALVADO', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL D''ADDUCTION D''EAU POTABLE DE LA REGIO', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL D''ASSAINISSEMENT DE LA VALLEE DU DAN', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL D''ASSAINISSEMENT DE SOLIERS GRENTHEVI', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL D''ASSAINISSEMENT DE ST ANDRE SUR ORNE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL D''ASSAINISSEMENT ST ANDRE MAY ST MART', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL DE CAEN HEROUVILL BIEVILLE EPRON', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL DE CAEN HEROUVILLE BIEVILLE EPRON', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL DE LA VALLEE DU DAN   MAIRIE DE BENOU', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL DU GRAND ODON  MAIRIE DE VERSON', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL EN EAU   MAIRIE D HERMANVILLE SUR MER', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL POUR L''ASSAINISSEMENT ET L''EVACUATION', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT INTERCOMMUNAL POUR LA VALORISATION ET L''ELIMINATION', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT MIXTE D ASSAINISSEMENT DE LA ZONE NORD OUEST DE AGG', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT MIXTE ET REALISATION DES TRAVAUX D UN CENTRE ROUTIE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT MIXTE POUR LA LUTTE CONTRE LES INNONDATIONS DE LA V', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT MIXTE TRAITEMENT VALORISATION DES DECHETS MENAGERS', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT MIXTE USINE CAPTAGE D EAU   MAIRIE DE CAEN', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SYNDICAT POUR LA VALORISATION ET L''ELIMINATION DES DECHETS D', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('OFFICE PUBLIC DE L HABITAT 87', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CAISSE ALLOCATIONS FAMILIALE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CH  COMMERCE INDUSTRIE LIMOGES HTE VIENN', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CHAMBRE D AGRICULTURE DE LA HAUTE VIENNE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CHAMBRE DE COMMERCE ET D INDUSTRIE DE LIMOGES', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CHAMBRE DES METIERS DE LA HAUTE VIENNE', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('CHAMBRE REG DE METIERS ET DE L''ARTISANAT DU LIMOUSIN', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE D''AGGLOMERATION D''HENIN-CARVIN', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('ETAT', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('DIRECTION DEPARTEMENTALE DE L EQUIPEMENT', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('MINISTERE DES TRANSPORTS', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('BPIFRANCE FINANCEMENT', 'AUTRE_PUB');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('COMMUNAUTE D''AGGLOMERATION DE SAINTES', 'EPCI');
INSERT INTO correction_typologie_proprietaire (ddenom, catpro) VALUES ('SOCIETE ANONYME D''ECONOMIE MIXTE IMMOBILIERE DE LA SAINTONGE', 'AMENAGEUR_PUB');
